git:
  depth: 5

language: node_js

node_js:
  - "10"

env:
  global:
    - RUBY_VERSION=2.4

before_install:
  - rvm use $RUBY_VERSION --install --binary --fuzzy

install:
  - npm ci
  - bundle install --deployment --retry=3 --clean

matrix:
  fast_finish: true

cache:
  directories:
    - "$HOME/.npm"
    - vendor/bundle

notifications:
  email: false
